[package]
name = "room4doom"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../build.rs"
default-run = "room4doom"

[[bin]]
name = "room4doom"
path = "src/main.rs"

[features]
default = ["trig_lut"]
safety_check = ["render-soft/safety_check"]
debug_draw = ["render-soft/debug_draw"]
debug_seg_clip = ["render-soft/debug_seg_clip"]
debug_seg_invert = ["render-soft/debug_seg_invert"]
hprof = ["render-soft/hprof"]
trig_lut = ["render-soft/trig_lut"]

[dependencies]
mimalloc = "0.1.43"
golem = { git = "https://github.com/flukejones/golem/" }

argh.workspace = true
input.workspace = true
menu-doom.workspace = true
gameplay.workspace = true
gamestate.workspace = true
gamestate-traits.workspace = true

intermission-doom.workspace = true
hud-doom.workspace = true
finale-doom.workspace = true
statusbar-doom.workspace = true

sound-traits.workspace = true
sound-sdl2.workspace = true
render-target.workspace = true
render-soft.workspace = true
wad.workspace = true

# utility deps
simplelog.workspace = true
dirs.workspace = true
nanoserde.workspace = true
coarse-prof.workspace = true

#[dev-dependencies]
#cargo-husky.workspace = true
