/// Used to build `SfxInfo`
pub(crate) struct SfxInfoBase {
    pub name: &'static str,
    pub singularity: bool,
    pub priority: i32,
}

impl SfxInfoBase {
    pub(crate) const fn new(name: &'static str, singularity: bool, priority: i32) -> Self {
        Self {
            name,
            singularity,
            priority,
        }
    }
}

/// The ordering here should match the `SfxEnum` ordering
pub(crate) const SFX_INFO_BASE: [SfxInfoBase; 109] = [
    SfxInfoBase::new("none", false, 0),
    SfxInfoBase::new("pistol", false, 64),
    SfxInfoBase::new("shotgn", false, 64),
    SfxInfoBase::new("sgcock", false, 64),
    SfxInfoBase::new("dshtgn", false, 64),
    SfxInfoBase::new("dbopn", false, 64),
    SfxInfoBase::new("dbcls", false, 64),
    SfxInfoBase::new("dbload", false, 64),
    SfxInfoBase::new("plasma", false, 64),
    SfxInfoBase::new("bfg", false, 64),
    SfxInfoBase::new("sawup", false, 64),
    SfxInfoBase::new("sawidl", false, 118),
    SfxInfoBase::new("sawful", false, 64),
    SfxInfoBase::new("sawhit", false, 64),
    SfxInfoBase::new("rlaunc", false, 64),
    SfxInfoBase::new("rxplod", false, 70),
    SfxInfoBase::new("firsht", false, 70),
    SfxInfoBase::new("firxpl", false, 70),
    SfxInfoBase::new("pstart", false, 100),
    SfxInfoBase::new("pstop", false, 100),
    SfxInfoBase::new("doropn", false, 100),
    SfxInfoBase::new("dorcls", false, 100),
    SfxInfoBase::new("stnmov", false, 119),
    SfxInfoBase::new("swtchn", false, 78),
    SfxInfoBase::new("swtchx", false, 78),
    SfxInfoBase::new("plpain", false, 96),
    SfxInfoBase::new("dmpain", false, 96),
    SfxInfoBase::new("popain", false, 96),
    SfxInfoBase::new("vipain", false, 96),
    SfxInfoBase::new("mnpain", false, 96),
    SfxInfoBase::new("pepain", false, 96),
    SfxInfoBase::new("slop", false, 78),
    SfxInfoBase::new("itemup", true, 78),
    SfxInfoBase::new("wpnup", true, 78),
    SfxInfoBase::new("oof", false, 96),
    SfxInfoBase::new("telept", false, 32),
    SfxInfoBase::new("posit1", true, 98),
    SfxInfoBase::new("posit2", true, 98),
    SfxInfoBase::new("posit3", true, 98),
    SfxInfoBase::new("bgsit1", true, 98),
    SfxInfoBase::new("bgsit2", true, 98),
    SfxInfoBase::new("sgtsit", true, 98),
    SfxInfoBase::new("cacsit", true, 98),
    SfxInfoBase::new("brssit", true, 94),
    SfxInfoBase::new("cybsit", true, 92),
    SfxInfoBase::new("spisit", true, 90),
    SfxInfoBase::new("bspsit", true, 90),
    SfxInfoBase::new("kntsit", true, 90),
    SfxInfoBase::new("vilsit", true, 90),
    SfxInfoBase::new("mansit", true, 90),
    SfxInfoBase::new("pesit", true, 90),
    SfxInfoBase::new("sklatk", false, 70),
    SfxInfoBase::new("sgtatk", false, 70),
    SfxInfoBase::new("skepch", false, 70),
    SfxInfoBase::new("vilatk", false, 70),
    SfxInfoBase::new("claw", false, 70),
    SfxInfoBase::new("skeswg", false, 70),
    SfxInfoBase::new("pldeth", false, 32),
    SfxInfoBase::new("pdiehi", false, 32),
    SfxInfoBase::new("podth1", false, 70),
    SfxInfoBase::new("podth2", false, 70),
    SfxInfoBase::new("podth3", false, 70),
    SfxInfoBase::new("bgdth1", false, 70),
    SfxInfoBase::new("bgdth2", false, 70),
    SfxInfoBase::new("sgtdth", false, 70),
    SfxInfoBase::new("cacdth", false, 70),
    SfxInfoBase::new("skldth", false, 70),
    SfxInfoBase::new("brsdth", false, 32),
    SfxInfoBase::new("cybdth", false, 32),
    SfxInfoBase::new("spidth", false, 32),
    SfxInfoBase::new("bspdth", false, 32),
    SfxInfoBase::new("vildth", false, 32),
    SfxInfoBase::new("kntdth", false, 32),
    SfxInfoBase::new("pedth", false, 32),
    SfxInfoBase::new("skedth", false, 32),
    SfxInfoBase::new("posact", true, 120),
    SfxInfoBase::new("bgact", true, 120),
    SfxInfoBase::new("dmact", true, 120),
    SfxInfoBase::new("bspact", true, 100),
    SfxInfoBase::new("bspwlk", true, 100),
    SfxInfoBase::new("vilact", true, 100),
    SfxInfoBase::new("noway", false, 78),
    SfxInfoBase::new("barexp", false, 60),
    SfxInfoBase::new("punch", false, 64),
    SfxInfoBase::new("hoof", false, 70),
    SfxInfoBase::new("metal", false, 70),
    SfxInfoBase::new("chgun", false, 64),
    SfxInfoBase::new("tink", false, 60),
    SfxInfoBase::new("bdopn", false, 100),
    SfxInfoBase::new("bdcls", false, 100),
    SfxInfoBase::new("itmbk", false, 100),
    SfxInfoBase::new("flame", false, 32),
    SfxInfoBase::new("flamst", false, 32),
    SfxInfoBase::new("getpow", false, 60),
    SfxInfoBase::new("bospit", false, 70),
    SfxInfoBase::new("boscub", false, 70),
    SfxInfoBase::new("bossit", false, 70),
    SfxInfoBase::new("bospn", false, 70),
    SfxInfoBase::new("bosdth", false, 70),
    SfxInfoBase::new("manatk", false, 70),
    SfxInfoBase::new("mandth", false, 70),
    SfxInfoBase::new("sssit", false, 70),
    SfxInfoBase::new("ssdth", false, 70),
    SfxInfoBase::new("keenpn", false, 70),
    SfxInfoBase::new("keendt", false, 70),
    SfxInfoBase::new("skeact", false, 70),
    SfxInfoBase::new("skesit", false, 70),
    SfxInfoBase::new("skeatk", false, 70),
    SfxInfoBase::new("radio", false, 60),
];
