[package]
name = "sound-sdl2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../../build.rs"

[features]

[dependencies]
sdl2.workspace = true
wad.workspace = true
sound-traits.workspace = true
opl2_emulator.workspace = true
log.workspace = true
glam.workspace = true
nanoserde.workspace = true
