[package]
name = "menu-doom"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gamestate-traits.workspace = true
sound-traits.workspace = true
wad.workspace = true
