[package]
name = "render-target"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../../build.rs"

[features]
safety_check = []
debug_draw = ["render-soft/debug_draw", "render3d/debug_draw"]
hprof = ["render-soft/hprof", "render3d/hprof"]

[dependencies]
gameplay.workspace = true
golem.workspace = true
sdl2.workspace = true
nanoserde.workspace = true
render-trait.workspace = true
render-soft.workspace = true
render3d.workspace = true
coarse-prof.workspace = true
