//! ReDoomEd-style map editor: Slint shell over [`LevelEditorState`].
//! UI callbacks return immediately; heavy work (BSP export) runs on worker threads.

mod assets;
mod boundary;
mod bsp_anim;
mod defaults;
mod gfx;
mod jobs;
mod launch;
mod level_editor;
mod light_anim;
#[cfg(target_os = "macos")]
mod macos;
mod menu;
mod png_export;
mod prefs;
mod project;
mod render;
mod state;
mod theme;
mod thing_info;
mod undo;
mod views;

use std::cell::RefCell;
use std::path::PathBuf;
use std::rc::Rc;

use argh::FromArgs;
use slint::ComponentHandle as _;

use crate::level_editor::{LevelEditorState, preview};
use crate::project::{open_from_options, open_project, refresh_all, refresh_recent};
use crate::state::SharedState;
use crate::views::{
    view_build_bsp, view_canvas, view_chrome, view_draw_settings, view_map_list,
    view_panels as panels, view_prefs, view_project_browser, view_project_settings, view_remap,
    view_sector_edit, view_status, view_tex_browser, view_tex_edit, view_tool, view_wall_edit,
    view_window,
};

// machine-generated by slint-build
#[allow(
    unused_qualifications,
    trivial_casts,
    trivial_numeric_casts,
    unused_import_braces,
    clippy::all,
    reason = "machine-generated by slint-build"
)]
pub(crate) mod generated {
    slint::include_modules!();
}
use generated::*;

/// ReDoomEd-style Doom map editor.
#[derive(FromArgs)]
struct Options {
    /// IWAD to open maps from
    #[argh(option)]
    iwad: Option<PathBuf>,
    /// PWAD to load alongside the IWAD (repeatable); appended after the IWAD so
    /// its lumps override (engine load order)
    #[argh(option)]
    pwad: Vec<PathBuf>,
    /// map name to open (e.g. E1M1); with --iwad
    #[argh(option)]
    map: Option<String>,
    /// open a DoomEd project (.dpr) for things/specials/textures
    #[argh(option)]
    project: Option<PathBuf>,
}

fn main() {
    simplelog::TermLogger::init(
        simplelog::LevelFilter::Info,
        simplelog::Config::default(),
        simplelog::TerminalMode::Mixed,
        simplelog::ColorChoice::Auto,
    )
    .expect("logger initializes once");

    install_platform();
    let options: Options = argh::from_env();
    let ui = EditorWindow::new().expect("Slint window creates");
    ui.set_is_macos(cfg!(target_os = "macos"));
    #[cfg(target_os = "macos")]
    macos::menu::install(&ui);
    #[cfg(target_os = "macos")]
    macos::window::install(&ui);
    let user_prefs = prefs::load_prefs();
    let mut app = LevelEditorState::new();
    app.grid = user_prefs.grid.max(1);
    app.snap = user_prefs.snap;
    app.snap_to_vertex = user_prefs.snap_to_vertex;
    app.snap_to_line = user_prefs.snap_to_line;
    let dark = prefs::resolve_dark(&user_prefs, false);
    let (name, variant) = if dark {
        (user_prefs.dark_theme.as_str(), opaline::ThemeVariant::Dark)
    } else {
        (
            user_prefs.light_theme.as_str(),
            opaline::ThemeVariant::Light,
        )
    };
    app.style = theme::resolve(name, variant).1;
    let iwad = options.iwad.clone();
    let shared = Rc::new(RefCell::new(SharedState::new(app, iwad, user_prefs)));

    {
        let weak = ui.as_weak();
        let s = shared.clone();
        let ctx = render::wgpu::capture(ui.window(), move || {
            let Some(ui) = weak.upgrade() else { return };
            // Clear colour is dropped if set before capture; re-push theme here.
            view_chrome::push_theme(&ui, &s);
            render::push_wgpu_frame(&ui, &s);
        });
        shared.borrow_mut().wgpu = ctx;
    }

    view_canvas::init(&ui, &shared);
    view_tool::init(&ui, &shared);
    view_build_bsp::init(&ui, &shared);
    menu::set_callbacks_menu(&ui, &shared);
    view_map_list::init(&ui, &shared);
    view_status::init(&ui, &shared);
    panels::init(&ui, &shared);
    view_draw_settings::init(&ui, &shared);
    view_tex_browser::init(&ui, &shared);
    view_remap::init(&ui, &shared);
    view_wall_edit::init(&ui, &shared);
    view_sector_edit::init(&ui, &shared);
    view_tex_edit::init(&ui, &shared);
    jobs::init(&ui, &shared);
    view_prefs::init(&ui, &shared);
    view_project_browser::init(&ui, &shared);
    view_project_settings::init(&ui, &shared);
    view_window::init(&ui, &shared);
    view_prefs::push_toolbar_position(&ui, &shared);
    preview::push_preview_mode(&ui, &shared);
    view_chrome::init(&ui, &shared);
    refresh_recent(&ui, &shared);

    if let Some(project) = &options.project {
        open_project(&ui, &shared, project);
        refresh_all(&ui, &shared);
    }
    open_from_options(&ui, &shared, &options);

    ui.run().expect("event loop runs");
}

/// femtovg-GL does not expose Device/Queue; femtovg-wgpu does.
const WGPU_RENDERER: &str = "femtovg-wgpu";

/// Installs winit + femtovg-wgpu backend. macOS: opaque titlebar prevents transparent bleed.
#[cfg(target_os = "macos")]
fn install_platform() {
    use winit::platform::macos::WindowAttributesExtMacOS as _;

    let mut backend = i_slint_backend_winit::Backend::builder()
        .with_renderer_name(WGPU_RENDERER)
        .build()
        .expect("winit wgpu backend");
    backend.window_attributes_hook = Some(Box::new(|attributes| {
        attributes
            .with_transparent(true)
            .with_titlebar_transparent(true)
            .with_fullsize_content_view(false)
    }));
    slint::platform::set_platform(Box::new(backend)).expect("set platform once");
    start_mcp_server();
}

#[cfg(not(target_os = "macos"))]
fn install_platform() {
    let backend = i_slint_backend_winit::Backend::builder()
        .with_renderer_name(WGPU_RENDERER)
        .build()
        .expect("winit wgpu backend");
    slint::platform::set_platform(Box::new(backend)).expect("set platform once");
    start_mcp_server();
}

/// Must be called explicitly — editor's custom platform bypasses the backend selector
/// that would otherwise start it. No-op unless `SLINT_MCP_PORT` is set.
#[cfg(feature = "slint-mcp")]
fn start_mcp_server() {
    if let Err(e) = i_slint_backend_testing::mcp_server::init() {
        log::warn!("Slint MCP server init failed: {e:?}");
    }
}

#[cfg(not(feature = "slint-mcp"))]
fn start_mcp_server() {}
